Fix encoding error while running tests
    SyntaxError: Non-ASCII character '\xc6' in file
    tests/regressiontests/utils/jslex.py on line 26, but no
    encoding declared; see http://python.org/dev/peps/pep-0263/ for
    details